source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Then_Example', :exclusive => true do
  pod "Then", :path => "../"
end

target 'Then_Tests', :exclusive => true do
  pod "Then", :path => "../"

  
end
